use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SecurityTestPlan {
    #[serde(default)]
    pub plan_id: String,
    pub base_url: String,
    pub tests: Vec<SecurityTest>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SecurityTest {
    pub id: String,
    pub flaw: String,
    pub target: Target,
    #[serde(default)]
    pub severity: String,
    #[serde(default)]
    pub payload_hint: String,
    /// Concrete payload value generated by AI (e.g. "' OR '1'='1", "<svg onload=alert(1)>").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    /// Where to inject the payload: "query:q", "body:username", "path", "header:X-Custom", "cookie:session".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(default)]
    pub oracle: Oracle,
    /// If true, executor will pause and ask user for approval before running this test.
    #[serde(default)]
    pub requires_confirmation: bool,
}

impl SecurityTest {
    /// Returns true if this test could modify data or cause side effects.
    pub fn is_destructive(&self) -> bool {
        let method = self.target.method.to_uppercase();
        let path_lower = self.target.path.to_lowercase();
        matches!(method.as_str(), "POST" | "PUT" | "DELETE" | "PATCH")
            && (path_lower.contains("password")
                || path_lower.contains("delete")
                || path_lower.contains("remove")
                || path_lower.contains("destroy")
                || path_lower.contains("purge")
                || path_lower.contains("reset")
                || path_lower.contains("disable")
                || path_lower.contains("create")
                || path_lower.contains("update")
                || path_lower.contains("modify")
                || path_lower.contains("submit")
                || path_lower.contains("transfer")
                || self.requires_confirmation)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Target {
    pub method: String,
    pub path: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct Oracle {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expect_status: Option<u16>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expect_contains: Option<String>,
}

impl SecurityTestPlan {
    pub fn with_id(mut self) -> Self {
        if self.plan_id.is_empty() {
            self.plan_id = uuid::Uuid::new_v4().to_string();
        }
        self
    }
}

/// Request sent to frontend when a destructive test needs user approval.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfirmationRequest {
    pub run_id: String,
    pub test_id: String,
    pub flaw: String,
    pub method: String,
    pub path: String,
    pub severity: String,
    pub payload_hint: String,
}

/// Response from frontend after user approves or rejects a destructive test.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfirmationResponse {
    pub test_id: String,
    pub approved: bool,
}

#[cfg(test)]
mod tests {
    use super::{Oracle, SecurityTest, SecurityTestPlan, Target};

    #[test]
    fn round_trips() {
        let plan = SecurityTestPlan {
            plan_id: "p1".into(),
            base_url: "https://fit.neu.edu.vn".into(),
            tests: vec![SecurityTest {
                id: "t1".into(),
                flaw: "idor".into(),
                target: Target {
                    method: "GET".into(),
                    path: "/codelab/subjects/nhap-mon".into(),
                },
                severity: "High".into(),
                payload_hint: "replace id".into(),
                payload: Some("6a17cbd5c8032287c4b7962e".into()),
                location: Some("path".into()),
                oracle: Oracle {
                    expect_status: Some(403),
                    expect_contains: None,
                },
                requires_confirmation: false,
            }],
        };
        let json = serde_json::to_string(&plan).unwrap();
        let decoded: SecurityTestPlan = serde_json::from_str(&json).unwrap();
        assert_eq!(plan, decoded);
    }

    #[test]
    fn is_destructive_detects_dangerous_tests() {
        let password_change = SecurityTest {
            id: "t1".into(),
            flaw: "csrf".into(),
            target: Target {
                method: "POST".into(),
                path: "/password/change".into(),
            },
            severity: "Medium".into(),
            payload_hint: "change password".into(),
            payload: None,
            location: None,
            oracle: Oracle::default(),
            requires_confirmation: false,
        };
        assert!(password_change.is_destructive());

        let safe_get = SecurityTest {
            id: "t2".into(),
            flaw: "xss".into(),
            target: Target {
                method: "GET".into(),
                path: "/search".into(),
            },
            severity: "High".into(),
            payload_hint: "inject script".into(),
            payload: None,
            location: None,
            oracle: Oracle::default(),
            requires_confirmation: false,
        };
        assert!(!safe_get.is_destructive());

        let explicit_confirm = SecurityTest {
            id: "t3".into(),
            flaw: "sqli".into(),
            target: Target {
                method: "POST".into(),
                path: "/api/data".into(),
            },
            severity: "Critical".into(),
            payload_hint: "sql injection".into(),
            payload: None,
            location: None,
            oracle: Oracle::default(),
            requires_confirmation: true,
        };
        assert!(explicit_confirm.is_destructive());
    }
}
