[package]
name = "api-tester-reporting"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
api-tester-analysis.workspace = true
api-tester-domain.workspace = true
serde_json.workspace = true
url.workspace = true

[lints]
workspace = true
